### ISSUE TITLE
Failing to configure with CUDA enabled

### ISSUE THREAD

**Issue by SAbdulah** [ecrc/ExaGeoStatCPP#34]
I'm having the following error when trying to run with the flag -c:

  CC       libstarpu_1.3_la-starpu_cublas.lo
  CC       libstarpu_1.3_la-starpu_cusparse.lo
In file included from ../include/starpu_cublas_v2.h:22,
                 from drivers/cuda/starpu_cublas.c:24:
/usr/include/cublas_v2.h:59:2: error: #error "It is an error to include both cublas.h and cublas_v2.h"
   59 | #error "It is an error to include both cublas.h and cublas_v2.h"
      |  ^~~~~
make[2]: *** [Makefile:2663: libstarpu_1.3_la-starpu_cublas.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/exouser/build/ExaGeoStatCPP/installdir/_deps/STARPU/starpu-src/src'
make[1]: *** [Makefile:2857: all-recursive] Error 1
make[1]: Leaving directory '/home/exouser/build/ExaGeoStatCPP/installdir/_deps/STARPU/starpu-src/src'
make: *** [Makefile:845: all-recursive] Error 1
CMake Error at cmake/macros/BuildDependency.cmake:116 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 2"

Call Stack (most recent call first):
  cmake/macros/ImportDependency.cmake:61 (BuildDependency)
  cmake/ImportStarPu.cmake:48 (ImportDependency)
  CMakeLists.txt:149 (include)

-- Configuring incomplete, errors occurred!
Full command:

./configure -ce
@alihakam830

**Comment by mahmoudElkarargyBS** [comment]
Hi,

I investigated this issue — you’re not alone. Under newer CUDA versions (notably CUDA 12), StarPU’s internal CUDA/BLAS drivers run into a strict header conflict: both **`cublas.h`** and **`cublas_v2.h`** end up being included, triggering:

```
#error "It is an error to include both cublas.h and cublas_v2.h"
```

This check is enforced in NVIDIA’s headers for recent CUDA toolkits. The conflict was often latent (or silently tolerated) in older CUDA releases, which is why builds with StarPU 1.3.10 used to work.

---

### What we tried and observed

* Updating **StarPU to v1.3.11** resolved the original `cublas.h` vs `cublas_v2.h` include conflict.
* However we have the same issue with Chameleon v1.0.0, So, We build **Chameleon v1.2.0** then introduced a new issue: the generated `.pc` files required a `cuda.pc`, which does not actually exist (NVIDIA does not ship it). This caused `pkg-config` to fail.
* We worked around this by creating a **dummy `cuda.pc`** pointing to our CUDA installation. With that in place, Chameleon built successfully, and the full dependency stack could compile.

---

### New blocker

However, due to changes in Chameleon between v1.1.0 and v1.2.0, our codebase now hits this compilation error:

```
/data/mahmoudelkarargy/Documents/KAUST/ExaGeoStatCPP/src/linear-algebra-solvers/concrete/chameleon/dst/ChameleonDST.cpp:127:24: error: there are no arguments to ‘BLKLDD’ that depend on a template parameter, so a declaration of ‘BLKLDD’ must be available [-fpermissive]
  127 |                 ldam = BLKLDD(A, m);
```

We also tested **Chameleon v1.3.0**, but that appears to require **StarPU ≥ 1.4**. Since we already confirmed our codebase breaks with StarPU 1.4, that path is not viable for us.

---

### Current options

At this point, we see two possible paths forward:

1. **Update our Chameleon-related code** to match the newer releases (which use different macro/function conventions).
2. **Require CUDA < 12** for our supported build chain, to avoid hitting the stricter header conflict in the first place. I tried again with ``` module load cuda/11.4 ``` and everything worked fine
